#!/bin/bash

while getopts 'rv' opt; do
  case "$opt" in
    r)
      echo "Processing option 'r'"
      ;;

    v)
      echo "Processing option 'v'"
      ;;

    ?)
      echo -e "Invalid command option.\nUsage: $(basename $0) [-r] [-v] file [file...]"
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"

echo "The complete list of arguments is $@"
echo "Total Number of Parameters: $#"

declare -A supportedMethods=( [gzip]=gunzip [bzip2]=bunzip2 [compress]=uncompress [zip]=unzip)

getFileFormat () {
  local fileOutput=$(file "$1" | tr '[:upper:]' '[:lower:]')
  IFS="': " read -r -a helper <<< "$fileOutput"
  echo "${helper[1]}"
}

isFormatSupported () {
  [[ " ${!supportedMethods[*]} " == *" $1 "* ]] && echo true || echo false
}

fileFormat=$(getFileFormat $1)
if $(isFormatSupported $fileFormat); then
  ${supportedMethods[$fileFormat]} $1
fi
