#!/bin/bash

while getopts 'rv' opt; do
  case "$opt" in
    r)
      recursive=true
      ;;

    v)
      verbose=true
      ;;

    ?)
      echo -e "Invalid command option.\nUsage: $(basename $0) [-r] [-v] file [file...]"
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"

compressedCount=0
uncompressedCount=0

echo "The complete list of arguments is $@"
echo "Total Number of Parameters: $#"

declare -A supportedMethods=( [gzip]="gunzip -f" [bzip2]="bunzip2 -f" [compress]="uncompress -f" [zip]="unzip -o")

getFileFormat () {
  local fileOutput=$(file "$1" | tr '[:upper:]' '[:lower:]')
  IFS="': " read -r -a helper <<< "$fileOutput"
  echo "${helper[1]}"
}

isFormatSupported () {
  [[ " ${!supportedMethods[*]} " == *" $1 "* ]] && echo true || echo false
}

handleFile () {
  local fileFormat=$(getFileFormat $1)
  if $(isFormatSupported $fileFormat); then
    ${supportedMethods[$fileFormat]} $1
    ((compressedCount++))  
  else  
    ((uncompressedCount++))  
  fi
  if $verbose; then
    $(isFormatSupported $fileFormat) && "Unpacking $1" || echo "Ignoring $1"
  fi

}

traverse () {
  for file in "$1"/*
  do
  if [ -f "${file}" ] ; then
      handleFile $file
  else
      echo "entering recursion with: ${file}"
      traverse $file
  fi
  done
}

for i in "$@"
do
  if [ -d $i ]
  then
    traverse $i
  elif [ -f $i ]
  then
    handleFile $i
  else
    echo "The given argument does not exist on the file system."
  fi
done

echo "Decompressed $compressedCount archive(s)"
exit $uncompressedCount